### ISSUE TITLE
linux 下引用包报错

### ISSUE THREAD

**Issue by zuoye520** [crazydogclone/snowflake#1]
作者您好，linux引用 snowflake.node 怎么解决?
`snowflake.node: invalid ELF header`

**Comment by crazydogclone** [comment]
你好，你直接在你的运行环境下，重新编译snowflake就好了发自我的华为手机-------- 原始邮件 --------主题：[crazydogclone/snowflake] linux 下引用包报错 (#1)发件人：zuoye520 收件人：crazydogclone/snowflake 抄送：Subscribed 作者您好，linux引用 snowflake.node 怎么解决?
snowflake.node: invalid ELF header

**Comment by zuoye520** [comment]
@crazydogclone 您好，是编译这个文件？snowflake.c 
编译命令如下：
gcc snowflake.c -o snowflake.node
报如下错误：
`fatal error: node_api.h: No such file or directory`

**Comment by zuoye520** [comment]
作者您好，linux下编译过不了。

# node-gyp configure &&node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@8.11.2 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/snowflake-master/src/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/8.11.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/8.11.2',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/8.11.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/snowflake-master/src',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@8.11.2 | linux | x64
make: Entering directory `/home/snowflake-master/src/build'
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/snowflakeLinux/snowflake.o
In file included from ../snowflake.c:7:0:
.././common.h:58:74: warning: backslash-newline at end of file [enabled by default]
 #define DECLARE_NAPI_GETTER(name, func)                                  \
 ^
../snowflake.c: In function ‘i64toa’:
../snowflake.c:46:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int i = 0;i < dest_len;++i)
   ^
../snowflake.c:46:3: note: use option -std=c99 or -std=gnu99 to compile your code
../snowflake.c:56:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int i = index; i < dest_len; ++i)
     ^
../snowflake.c: In function ‘nextId’:
../snowflake.c:115:5: warning: passing argument 4 of ‘napi_get_cb_info’ from incompatible pointer type [enabled by default]
     NAPI_CALL(env, napi_get_cb_info(env, info, &arg_len, &arg, &argThis, NULL));
     ^
In file included from ../snowflake.c:2:0:
/root/.node-gyp/8.11.2/include/node/node_api.h:333:25: note: expected ‘struct napi_value__ **’ but argument is of type ‘struct napi_value__ * (*)[2]’
 NAPI_EXTERN napi_status napi_get_cb_info(
                         ^
make: *** [Release/obj.target/snowflakeLinux/snowflake.o] Error 1
make: Leaving directory `/home/snowflake-master/src/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.10.0-514.26.2.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "build"
gyp ERR! cwd /home/snowflake-master/src
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v4.0.0
gyp ERR! not ok

**Comment by xushuyi888** [comment]
修改了源码，windows编译通过
cd src 
node-gyp rebuild

`

#include <node_api.h>
#include <string.h>
#ifdef WIN32
#include <windows.h>
#include "time.h"  
#else
#include <sys/time.h>
#endif
#include <stdlib.h>
#include <math.h>
#include "./common.h"

//各个数据所在位偏移
int workerIdBits = 5;
int dataCenterIdBits = 5;
int sequenceBits = 12;

int maxWorkerId = -1;
int maxDataCenterId = -1;
int sequenceMask = -1;

int workerIdShift, dataCenterIdShift, timestampLeftShift;

uint64_t lastTimestamp = (uint64_t)0;

unsigned int sequence = 0;

#ifdef WIN32
int gettimeofday(struct timeval *tp, void *tzp)
{
  time_t clock;
  struct tm tm;
  SYSTEMTIME wtm;
  GetLocalTime(&wtm);
  tm.tm_year   = wtm.wYear - 1900;
  tm.tm_mon   = wtm.wMonth - 1;
  tm.tm_mday   = wtm.wDay;
  tm.tm_hour   = wtm.wHour;
  tm.tm_min   = wtm.wMinute;
  tm.tm_sec   = wtm.wSecond;
  tm. tm_isdst  = -1;
  clock = mktime(&tm);
  tp->tv_sec = clock;
  tp->tv_usec = wtm.wMilliseconds * 1000;
  return (0);
}
#endif

 int timeGen(uint64_t* time){
 	struct timeval tv;
 	int res;
 	res = gettimeofday(&tv, NULL);
 	if(!res){
 		*time = (uint64_t)tv.tv_sec*(uint64_t)1000 + (uint64_t)tv.tv_usec/(uint64_t)1000;
 	}
 	return res;
 }

 uint64_t tilNextMillis(uint64_t* lastTimestamp){
 	uint64_t timestamp;
 	timeGen(&timestamp);
 	while (timestamp <= *lastTimestamp) {
     timeGen(&timestamp);
   }
   return timestamp;
 }

char* i64toa(uint64_t src, char* dest, int dest_len){
  int index = -1,value = 0;
  int i;
  for (i = 0;i < dest_len;++i)
  {
    value = src % 10;
    if(value != 0) index = dest_len - i - 1;
    dest[dest_len - i - 1] = (char)('0' + src % 10);
    src /= 10;
  }

  if(index != 0)
  {
    int i;
    for (i = index; i < dest_len; ++i)
    {
      *(dest + i - index) = *(dest + i);
    }
    *(dest + dest_len - index) = '\0';
  }

  if(index == -1)
  {
    *(dest) = '0';
    *(dest + 1) = '\0';
  }

  return dest;
}

napi_value MaxWorkerId(napi_env env, napi_callback_info info) {
  napi_value res;

  if(maxWorkerId == -1){
    maxWorkerId = pow(2, workerIdBits) - 1;
  }

  NAPI_CALL(env, napi_create_int32(env, maxWorkerId, &res));

  return res;
}

napi_value MaxDataCenterId(napi_env env, napi_callback_info info) {
  napi_value res;

  if(maxDataCenterId == -1){
    maxDataCenterId = pow(2, dataCenterIdBits) - 1;
  }

  NAPI_CALL(env, napi_create_int32(env, maxDataCenterId, &res));

  return res;
}

napi_value init(napi_env env, napi_callback_info info) {
  napi_value res;
  
  maxWorkerId = pow(2, workerIdBits) - 1;
  maxDataCenterId = pow(2, dataCenterIdBits) - 1;
  sequenceMask = pow(2, sequenceBits) - 1;

  workerIdShift = sequenceBits;
  dataCenterIdShift = sequenceBits + workerIdBits;
  timestampLeftShift = sequenceBits + workerIdBits + dataCenterIdBits;

  NAPI_CALL(env, napi_create_int32(env, 1, &res));

  return res;
}

napi_value nextId(napi_env env, napi_callback_info info) {
    napi_value arg[2], argThis, result;
    size_t arg_len = 2;
    NAPI_CALL(env, napi_get_cb_info(env, info, &arg_len, &arg, &argThis, NULL));
    int workerId,dataCenterId;
    uint64_t timestamp = (uint64_t)0;

    NAPI_CALL(env, napi_get_value_int32(env, arg[0], &workerId));
    NAPI_CALL(env, napi_get_value_int32(env, arg[1], &dataCenterId));
//    NAPI_CALL(env, napi_get_value_int64(env, arg[2], &timestamp));

    timeGen(&timestamp);
    if(lastTimestamp == timestamp){
    	sequence = (sequence + 1) & sequenceMask;
    	if(sequence == 0){
    	    timestamp = tilNextMillis(&lastTimestamp);
//        NAPI_CALL(env, napi_create_int64(env, -1, &result));
//        return result;
    	}
    }else{
    	sequence = 0;
    }

    if (timestamp < lastTimestamp) {
      napi_throw_error(env, NULL, "Clock moved backwards.");
    }

    lastTimestamp = timestamp;

    uint64_t i64nextId = ((timestamp) << timestampLeftShift | (dataCenterId << dataCenterIdShift) |
    	(workerId << workerIdShift) | sequence);

    char res[20] = "\0";
    i64toa(i64nextId, res, 19);

//    NAPI_CALL(env, napi_create_object(env, &result));
//
//    napi_value int64, string;
//
//    NAPI_CALL(env, napi_create_int64(env, i64nextId, &int64));
//    NAPI_CALL(env, napi_create_string_utf8(env, res, NAPI_AUTO_LENGTH, &string));
//
//    NAPI_CALL(env, napi_set_named_property(env, result, "int64", int64));
//    NAPI_CALL(env, napi_set_named_property(env, result, "string", string));

    NAPI_CALL(env, napi_create_string_utf8(env, res, NAPI_AUTO_LENGTH, &result));

    return result;
}


napi_value Init(napi_env env, napi_value exports) {
  napi_property_descriptor desc[] = {
  		DECLARE_NAPI_PROPERTY("nextId", nextId),
  		DECLARE_NAPI_PROPERTY("init", init),
  		DECLARE_NAPI_PROPERTY("maxWorkerId", MaxWorkerId),
  		DECLARE_NAPI_PROPERTY("maxDataCenterId", MaxDataCenterId)
  	};
  NAPI_CALL(env, napi_define_properties(env, exports, sizeof(desc) / sizeof(desc[0]), desc));
  return exports;
}

NAPI_MODULE(NODE_GYP_MODULE_NAME, Init)
`
